# Generated by Django 6.1.1 on 2026-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='título')),
                ('slug', models.SlugField(unique=True, verbose_name='identificador')),
                ('document_type', models.CharField(choices=[('word', 'Documento Word'), ('excel', 'Libro Excel'), ('powerpoint', 'Presentación PowerPoint')], max_length=20, verbose_name='tipo')),
                ('summary', models.TextField(verbose_name='resumen')),
                ('file', models.FileField(upload_to='documents/', verbose_name='archivo')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['document_type', 'title'],
            },
        ),
    ]
