# Generated by Django 6.1.1 on 2026-09-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='documents/pdf/', verbose_name='versión PDF para lectura'),
        ),
    ]
